# Generated by Django 4.2.1 on 2023-05-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_signin_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signin',
            new_name='Signup',
        ),
    ]
